export const LOGIN = '/login'
export const DASHBOARD = '/dashboard'
export const DASHBOARD_OVERVIEW = '/dashboard/overview'
export const DASHBOARD_TASKS = '/dashboard/tasks'
export const DASHBOARD_CONTACTS = '/dashboard/contacts'
